<a href="https://colab.research.google.com/github/princeiiitk/Sentiment-Analysis/blob/main/Sentimat_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/princeiiitk/Sentiment-Analysis

Cloning into 'Sentiment-Analysis'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 25.33 MiB | 15.56 MiB/s, done.
fatal: destination path 'Sentiment-Analysis' already exists and is not an empty directory.

In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('/content/Sentiment-Analysis/IMDB Dataset.csv')

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [ ]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(418)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:

df.duplicated().sum()

np.int64(0)

# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [ ]:
import re
def remove_tags(raw_text):
  cleaned_text=re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [ ]:
df['review']=df['review'].apply(remove_tags)

In [ ]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [ ]:
df['review']=df['review'].apply(lambda x:x.lower())

In [ ]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

sw_list = stopwords.words('english')

df['review']=df['review'].apply(lambda x:[wordlist for wordlist in x.split() if wordlist not in sw_list]).apply(lambda x:' '.join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production. filming technique...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy (jake) thi...
4        petter mattei's "love time money" visually stu...
                               ...
49995    thought movie right good job. creative origina...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art, fans ex...
Name: review, Length: 49582, dtype: object

In [ ]:
X=df['review']
y=df['sentiment']

In [ ]:
X

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production. filming technique...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy (jake) thi...
4        petter mattei's "love time money" visually stu...
                               ...
49995    thought movie right good job. creative origina...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art, fans ex...
Name: review, Length: 49582, dtype: object

In [ ]:
y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 49582, dtype: object

In [ ]:
X_small = X[:2000]
y_small = y[:2000]

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
y_test

array([1, 1, 1, ..., 1, 0, 1])

In [ ]:
X_train.shape

(39665,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
X_train_transformed=cv.fit_transform(X_train).toarray()
X_test_transformed=cv.transform(X_test).toarray()

In [ ]:
X_train_transformed.shape

(39665, 5000)

# Naive Bayes (GaussianNB) Model Training for Classification

In [ ]:
from sklearn.naive_bayes import GaussianNB


model=GaussianNB()
model.fit(X_train_transformed,y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred=model.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

0.7424624382373701

In [ ]:
confusion_matrix(y_test,y_pred)

array([[4248,  661],
       [1893, 3115]])

# Naive Bayes (MultinomialNB) Model Training for Text Classification

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model2=MultinomialNB()
model2.fit(X_train_transformed,y_train)

In [ ]:
y_pred=model.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

# Random Forest Classifier Model Training for Machine Learning Classification

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model3=RandomForestClassifier()
model3.fit(X_train_transformed,y_train)

In [ ]:
y_pred=model.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

In [ ]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

In [ ]:
cv=CountVectorizer(ngram_range=(1,2),max_features=5000)
X_train_bow=cv.fit_transform(X_train).toarray()
X_test_bow=cv.transform(X_test).toarray()
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

# Using RNN

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

# 1. Tokenize
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(X)

# 2. Convert to sequences
sequences = tokenizer.texts_to_sequences(X)
sequences

[[3,
  2062,
  984,
  59,
  219,
  3142,
  308,
  3156,
  107,
  540,
  510,
  132,
  7,
  21,
  60,
  3182,
  3142,
  53,
  486,
  175,
  107,
  573,
  56,
  1674,
  132,
  43,
  2279,
  43,
  2538,
  1406,
  286,
  486,
  3765,
  270,
  265,
  573,
  6,
  344,
  3142,
  263,
  2493,
  991,
  2660,
  1357,
  445,
  4600,
  2430,
  1127,
  2932,
  303,
  208,
  4889,
  445,
  253,
  32,
  4991,
  2394,
  488,
  177,
  234,
  35,
  129,
  147,
  44,
  10,
  52,
  192,
  1259,
  43,
  606,
  98,
  178,
  185,
  2983,
  751,
  86,
  1246,
  4100,
  2458,
  1166,
  751,
  1374,
  751,
  802,
  3142,
  872,
  89,
  21,
  308,
  45,
  113,
  3182,
  1565,
  2201,
  52,
  1529,
  6,
  197,
  488,
  1342,
  1208,
  3142,
  95,
  208,
  1989,
  2088,
  486,
  486,
  4940,
  2947,
  413,
  554,
  17,
  147,
  6,
  14,
  567,
  625,
  577,
  1127,
  606,
  490,
  843,
  1954,
  1127,
  474,
  59,
  3142,
  105,
  335,
  3753,
  3314,
  720,
  1532,
  17,
  1145,
  4052,
  396],
 [302,
  42,
  261,
  1313,
  2914,
  65,
  8,
  2331,
  1519,
  319,
  441,
  191,
  1780,
  353,
  322,
  61,
  482,
  14,
  2216,
  411,
  4504,
  2335,
  95,
  2252,
  3270,
  290,
  278,
  13,
  709,
  1762,
  14,
  187,
  59,
  316,
  2336,
  322,
  4316,
  261,
  3,
  18,
  106,
  39,
  1780,
  11,
  179,
  253,
  42,
  83,
  946,
  2883,
  467,
  153,
  265,
  2146,
  3070,
  1217,
  1110,
  4926,
  207,
  1761,
  4505,
  501,
  53,
  3637,
  647,
  501,
  970,
  79,
  2241,
  1925,
  14,
  124],
 [96,
  302,
  24,
  1084,
  8,
  796,
  1423,
  2593,
  1162,
  824,
  685,
  59,
  562,
  2279,
  106,
  36,
  4038,
  321,
  1854,
  28,
  1420,
  9,
  14,
  1511,
  408,
  105,
  593,
  883,
  952,
  122,
  140,
  2859,
  96,
  2994,
  2904,
  1990,
  51,
  1329,
  1062,
  306,
  32,
  82,
  2015,
  37,
  46,
  1386,
  3,
  1236,
  62,
  2983,
  52,
  2064,
  35,
  1435,
  1252,
  1182,
  1177,
  1365,
  107,
  766,
  3593,
  92,
  163,
  46,
  105,
  542,
  2191,
  2877,
  123,
  2582,
  18,
  106,
  56,
  13,
  258],
 [605,
  125,
  141,
  42,
  332,
  3610,
  1176,
  125,
  940,
  4232,
  728,
  916,
  8,
  46,
  1,
  1792,
  1244,
  1035,
  3610,
  1011,
  335,
  413,
  940,
  499,
  21,
  76,
  23,
  2,
  110,
  1091,
  618,
  360,
  360,
  1,
  1648,
  728,
  4,
  58,
  39,
  3610,
  4232,
  371,
  4053,
  2,
  775,
  13,
  662,
  1,
  210,
  197,
  360,
  3812,
  618,
  3260,
  246,
  69,
  14,
  305,
  728,
  4637,
  3250,
  559,
  3610,
  2718,
  161],
 [37,
  8,
  201,
  2089,
  1361,
  2,
  29,
  349,
  1501,
  82,
  4284,
  3271,
  304,
  4450,
  1,
  90,
  915,
  82,
  201,
  575,
  928,
  20,
  189,
  1068,
  2437,
  1803,
  200,
  683,
  73,
  108,
  917,
  8,
  77,
  798,
  189,
  28,
  826,
  3739,
  3,
  3208,
  3,
  24,
  66,
  275,
  312,
  3,
  90,
  41,
  846,
  122,
  2867,
  2,
  3340,
  72,
  521,
  13,
  20,
  330,
  87,
  330,
  7,
  60,
  3,
  120,
  3375,
  345,
  189,
  4753,
  3,
  97,
  445,
  540,
  40,
  183,
  304,
  4450,
  75,
  4451,
  3,
  327,
  20,
  2437,
  7,
  38,
  5,
  349,
  374,
  1263,
  3895,
  2809,
  411,
  279,
  947,
  81,
  23,
  28,
  118,
  1049,
  1183,
  558,
  349,
  5,
  1986,
  275,
  67],
 [143,
  74,
  8,
  434,
  1,
  12,
  3822,
  3523,
  1072,
  256,
  35,
  120,
  65,
  377,
  33,
  1031,
  114,
  142,
  2347,
  62,
  754,
  145,
  899,
  1660,
  435,
  4301,
  2036,
  3,
  278,
  2134,
  497,
  2970,
  266,
  809,
  458,
  4,
  1808,
  171,
  379,
  71,
  150,
  29,
  4174,
  476,
  691,
  1400,
  87,
  745,
  2533,
  3510,
  171,
  1],
 [152,
  10,
  4,
  13,
  1982,
  112,
  538,
  10,
  658,
  57,
  464,
  2348,
  132,
  44,
  2102,
  226,
  363,
  144,
  79,
  1172,
  190,
  1994,
  77,
  1573,
  2280,
  1183,
  269,
  580,
  976,
  144,
  10,
  67,
  87,
  904,
  1088,
  338,
  24,
  1291,
  4,
  550,
  32,
  144,
  32,
  25,
  177,
  24,
  170,
  95,
  2878,
  52,
  10,
  241,
  247,
  831,
  723,
  1573,
  2280,
  340,
  10,
  69,
  320,
  10,
  288,
  417,
  483,
  710,
  4801,
  340,
  110,
  56,
  1496,
  6],
 [43,
  399,
  1382,
  4101,
  229,
  1666,
  21,
  3052,
  21,
  617,
  641,
  62,
  426,
  83,
  3367,
  101,
  43,
  11,
  64,
  1488,
  3661,
  512,
  364,
  8,
  538,
  493,
  278,
  129,
  43,
  2958,
  401,
  2281,
  16,
  276,
  119,
  16,
  2583,
  336,
  2846,
  43,
  143,
  51,
  824,
  75,
  154,
  170,
  4890,
  437,
  116,
  81,
  19,
  2475,
  1070,
  1499,
  3,
  2365,
  3511,
  13,
  1044,
  347,
  110,
  103,
  140,
  318,
  1089,
  116,
  81,
  22,
  43,
  557,
  928,
  313,
  43,
  280,
  91,
  170,
  51,
  824],
 [1085,
  700,
  2,
  164,
  847,
  59,
  2,
  16,
  1343,
  33,
  30,
  278,
  3,
  151,
  280,
  119,
  79,
  24,
  709,
  1731,
  688,
  748,
  653,
  7,
  544,
  516,
  784,
  596,
  3005,
  157,
  249,
  571,
  114,
  2,
  196,
  607,
  1565,
  256,
  1466,
  1631,
  590,
  13,
  48,
  816,
  2,
  60,
  656,
  219,
  484,
  4506,
  129,
  40,
  145,
  128,
  90,
  136,
  130,
  692,
  3,
  1644],
 [4, 116, 2117, 4, 1, 92, 65, 37, 1, 517, 9, 1534, 337, 6, 18, 1146],
 [4400,
  1094,
  3,
  2608,
  30,
  1122,
  350,
  89,
  176,
  153,
  734,
  741,
  21,
  954,
  86,
  64,
  1,
  75,
  537,
  64,
  1488,
  2836,
  267,
  240,
  2,
  1532,
  35,
  361,
  953,
  86,
  123,
  28,
  776,
  343,
  531,
  44,
  726,
  2,
  10,
  1259,
  3740,
  355,
  55,
  662,
  47,
  260,
  541,
  66,
  1272],
 [113,
  1,
  1601,
  294,
  159,
  2152,
  50,
  97,
  3341,
  1828,
  252,
  107,
  824,
  88,
  88,
  297,
  92,
  464,
  76,
  833,
  404,
  30,
  2289,
  51,
  1358,
  2111,
  690,
  457,
  25,
  548,
  1873,
  533,
  220,
  163,
  137,
  477,
  2414,
  590,
  3552,
  690,
  1003,
  48,
  369,
  15,
  659,
  2661,
  1601,
  209,
  65,
  637,
  1596,
  37,
  4054,
  372,
  149,
  209,
  215,
  113,
  2166,
  294,
  342,
  233,
  4992,
  314,
  2,
  1703,
  465,
  1348,
  122,
  139,
  136,
  12,
  23,
  582,
  539,
  14,
  4268,
  2111,
  2147],
 [4525,
  97,
  235,
  67,
  32,
  809,
  424,
  1,
  182,
  4525,
  3,
  4426,
  599,
  1157,
  2599,
  265,
  129,
  1372,
  100,
  520,
  9,
  375,
  9,
  20,
  424,
  764,
  930,
  2223,
  878,
  2673,
  129,
  1372,
  55,
  349,
  4426,
  203,
  248,
  473,
  175,
  349,
  4426,
  188,
  200,
  370,
  1817,
  56,
  1294,
  188,
  1294,
  68,
  22,
  86,
  97,
  1,
  704,
  178,
  4,
  46,
  624,
  157,
  331,
  956,
  1828,
  94,
  75,
  38,
  1,
  86,
  20,
  11,
  3833,
  198,
  126,
  4889,
  113,
  21,
  312,
  2049,
  11,
  41,
  504,
  4,
  4704,
  131,
  94,
  688,
  2,
  584,
  13,
  387,
  1045,
  1567,
  717,
  157,
  136,
  1163,
  344,
  3376,
  250,
  930,
  2223,
  878,
  1693,
  1254,
  194,
  1532,
  107,
  4142,
  184,
  210,
  95,
  241,
  903,
  1543,
  9,
  699,
  129,
  572,
  1372,
  491,
  56,
  488,
  2878,
  693,
  198,
  56,
  13,
  1,
  593,
  1470,
  198,
  4426,
  474,
  1077,
  2615,
  166,
  83,
  187,
  4245,
  10,
  4426,
  5,
  67,
  3577,
  2,
  241,
  1740,
  916,
  53,
  126,
  4160,
  3578,
  50,
  176,
  71,
  333,
  1,
  129,
  1372,
  102,
  1394,
  2878,
  93,
  56,
  1383,
  120,
  556,
  3942,
  71,
  2878,
  1118,
  21,
  188,
  134,
  165],
 [81,
  157,
  2167,
  2167,
  343,
  44,
  1036,
  172,
  658,
  2167,
  4891,
  2674,
  55,
  5,
  127,
  926,
  4835,
  434,
  2167,
  41,
  41,
  676,
  2868,
  677,
  55,
  662,
  924,
  104,
  585,
  491,
  4302,
  3053,
  44,
  820,
  820,
  128,
  633,
  320,
  2971,
  54,
  523,
  35,
  301,
  76,
  52,
  1,
  546,
  178,
  508,
  6],
 [712,
  1,
  188,
  3695,
  335,
  721,
  3,
  61,
  660,
  235,
  1763,
  16,
  66,
  5,
  60,
  1,
  653,
  7,
  49,
  1809,
  1,
  1303],
 [146,
  1366,
  2515,
  53,
  883,
  3,
  2282,
  1292,
  1617,
  2,
  45,
  33,
  339,
  4,
  208,
  273,
  2,
  1067,
  446,
  1751,
  28,
  1081,
  351,
  421,
  86,
  154,
  17,
  487,
  3,
  2984,
  1771,
  6,
  426,
  4416,
  84,
  565,
  149,
  661,
  2294,
  190,
  1773,
  419,
  555,
  1199,
  3368,
  1829,
  780,
  1303,
  305,
  497,
  103,
  3,
  1277,
  4,
  1353,
  2016,
  16,
  927,
  2,
  201,
  26,
  914,
  379,
  4866,
  2516],
 [30,
  238,
  3,
  161,
  16,
  2,
  923,
  1877,
  2192,
  2,
  328,
  227,
  115,
  127,
  81,
  1663,
  171,
  1403,
  3920,
  2548,
  658,
  107,
  135,
  34,
  2685,
  578,
  2050,
  225,
  129,
  4401,
  1769,
  12,
  936,
  343,
  3885,
  869,
  2,
  3524,
  217,
  195,
  52,
  16,
  2,
  259,
  2192,
  884,
  225,
  15,
  488],
 [1,
  22,
  3,
  250,
  69,
  280,
  25,
  402,
  695,
  472,
  3,
  690,
  66,
  492,
  34,
  894,
  3175,
  551,
  3,
  2731,
  472,
  66,
  807,
  470,
  97,
  16,
  1459,
  373,
  2168,
  161,
  53,
  2549,
  25,
  233,
  1621,
  3006,
  2645,
  7,
  1278,
  50,
  48,
  2549,
  383,
  50,
  65,
  233,
  1621,
  3,
  7,
  4620,
  1459,
  362,
  540,
  4,
  2959,
  4620,
  957,
  1687,
  1355,
  30,
  770,
  6,
  1355,
  171,
  54,
  126,
  1459,
  1508,
  1786,
  683,
  3006,
  417,
  166,
  2645,
  364,
  8,
  205,
  289,
  3780,
  12,
  254,
  3315,
  3780,
  1164,
  1,
  26,
  1091,
  2573,
  1,
  1168,
  1,
  15,
  255,
  280,
  58,
  1351,
  52,
  128,
  506,
  201],
 [293,
  2,
  6,
  21,
  2,
  197,
  352,
  345,
  368,
  1289,
  4452,
  57,
  1279,
  465,
  541,
  711,
  352,
  1907,
  2152,
  661,
  3018,
  2,
  19,
  1225,
  4526,
  199,
  2153,
  27,
  3,
  120,
  228,
  1429,
  156,
  586,
  75,
  174,
  418,
  513,
  288,
  41,
  7,
  352,
  577,
  1321,
  97,
  789,
  352,
  777,
  2016,
  147,
  10,
  37,
  758,
  310,
  33,
  2,
  4,
  6],
 [280,
  2,
  110,
  58,
  2194,
  1815,
  521,
  12,
  21,
  721,
  569,
  584,
  3896,
  3722,
  521,
  2185,
  12,
  5,
  10,
  837,
  395,
  238,
  1081,
  198,
  12,
  1724,
  10,
  22,
  129,
  47,
  2,
  118,
  672,
  133,
  1282,
  99,
  1219,
  20,
  225,
  48,
  2564,
  39,
  26,
  1950,
  281,
  549,
  279,
  2],
 [928,
  639,
  154,
  2202,
  762,
  11,
  154,
  748,
  25,
  262,
  121,
  262,
  183,
  262,
  8,
  1056,
  639,
  154,
  2388,
  8,
  2112,
  1534,
  542,
  3,
  97,
  898,
  167,
  3125,
  2388,
  2722,
  3369,
  2750,
  2793,
  38,
  1954,
  271,
  2,
  3,
  2584,
  2509,
  9,
  1252,
  17,
  159,
  801,
  1609,
  94,
  751,
  1773,
  68,
  2995,
  336,
  1470,
  892,
  3543,
  3424,
  892,
  844,
  95,
  37,
  223,
  79,
  788,
  1070,
  40,
  74,
  1425,
  3943,
  756,
  105,
  1632,
  1511,
  411,
  3474,
  1354,
  145,
  3512,
  1257,
  1316,
  2847,
  49,
  35,
  1375,
  1747,
  1340,
  91,
  414,
  11,
  72,
  4,
  3261,
  1227,
  34,
  155,
  234,
  664,
  110,
  56,
  1037,
  199,
  3781,
  16,
  121,
  179,
  1747,
  703,
  3512,
  304,
  2037,
  331,
  91,
  251,
  259,
  130,
  3512,
  797,
  5,
  4704,
  177,
  751,
  47,
  2103,
  26,
  35,
  2406,
  38,
  1352,
  386,
  259,
  164,
  3,
  1545,
  4198],
 [291,
  550,
  404,
  1,
  74,
  52,
  127,
  506,
  8,
  201,
  95,
  151,
  404,
  1,
  8,
  9,
  344,
  404,
  1,
  4,
  1150,
  1,
  923,
  1344,
  23,
  5,
  1,
  12,
  123,
  74,
  61,
  2065,
  1574,
  745,
  16,
  374,
  108,
  767,
  1082,
  119,
  64,
  119,
  7,
  1,
  2848,
  271,
  1878,
  3,
  2459,
  312,
  26,
  75,
  1060,
  128,
  42,
  130,
  46,
  1,
  351,
  860,
  252,
  287,
  1240,
  167,
  65,
  60,
  179,
  860,
  48,
  260,
  890,
  1177,
  850,
  402,
  1293,
  1857,
  3277,
  9,
  565,
  404,
  25,
  51,
  103,
  844,
  1316,
  29],
 [326,
  1361,
  1,
  140,
  367,
  413,
  29,
  6,
  2452,
  6,
  15,
  150,
  2831,
  1,
  168,
  138,
  169,
  51,
  337,
  6,
  109,
  131,
  1394,
  214,
  8,
  2048,
  469,
  114,
  11,
  284,
  3712,
  6],
 [21,
  74,
  830,
  17,
  83,
  642,
  184,
  131,
  2483,
  235,
  115,
  415,
  98,
  44,
  237,
  29,
  2158,
  8,
  404,
  4,
  348,
  404,
  25,
  496,
  1055,
  4,
  25,
  78,
  626,
  162,
  1,
  21,
  179,
  162,
  90,
  4,
  76,
  581,
  404,
  1,
  1878,
  3544,
  2224,
  4776,
  2483,
  179,
  162,
  1,
  178,
  4317,
  7,
  753,
  16,
  607,
  9,
  341,
  293,
  2158,
  98,
  607,
  3,
  53,
  1,
  293,
  673,
  266,
  405,
  273,
  266,
  206,
  3544,
  291,
  290,
  3782,
  72,
  341,
  1586,
  4993,
  330,
  108,
  753,
  321,
  2252,
  167,
  523,
  2171,
  3494,
  1279,
  93,
  1890,
  174,
  1727,
  1704,
  60,
  714,
  4664,
  537,
  700,
  4,
  4686,
  4638,
  1793,
  2996,
  190,
  1103,
  800,
  1158,
  24,
  1111,
  259,
  1,
  1825,
  8,
  2096,
  3741,
  43,
  66,
  1546,
  4941,
  1712,
  2080,
  404,
  1,
  224,
  274,
  86,
  1316,
  29,
  3424,
  496,
  8,
  656,
  1,
  246,
  69,
  2159,
  367,
  69,
  1833,
  76,
  103,
  6,
  1797,
  2229,
  246,
  69,
  729,
  86,
  15,
  256,
  16,
  150,
  188,
  804,
  75,
  24,
  23,
  150,
  6,
  335,
  150,
  1031],
 [151,
  1,
  113,
  19,
  1951,
  128,
  1042,
  3662,
  27,
  3896,
  350,
  1042,
  462,
  61,
  2,
  18,
  13,
  1483,
  1,
  134,
  2072,
  2539,
  15,
  47,
  443,
  80,
  1512,
  355,
  279,
  38,
  154,
  1668,
  1,
  565,
  637,
  192,
  34,
  371,
  1479,
  2695,
  29,
  58,
  807,
  1046,
  12,
  1,
  199,
  91,
  17,
  67,
  135,
  116,
  132,
  894,
  873,
  713,
  4,
  3,
  32,
  642,
  285,
  282,
  25,
  113,
  57,
  4867,
  9,
  5,
  3,
  1540],
 [3058,
  3579,
  12,
  185,
  42,
  1774,
  3058,
  1229,
  39,
  63,
  923,
  656,
  1682,
  2185,
  1268,
  2195,
  3058,
  395,
  5,
  443,
  207,
  2470,
  339,
  879,
  3058,
  3579,
  27,
  117,
  797,
  3696,
  34,
  205,
  3696,
  1535,
  117,
  3579,
  1247,
  18,
  202,
  323,
  6,
  18,
  634,
  26,
  1873,
  653,
  4333,
  391,
  63,
  1,
  250,
  2794,
  2738,
  348,
  2977],
 [7,
  2527,
  4346,
  838,
  1154,
  3851,
  231,
  1511,
  408,
  19,
  3,
  947,
  73,
  2028,
  3183,
  304,
  3262,
  67,
  3991,
  1108,
  2209,
  694,
  1764,
  55,
  278,
  1818,
  40,
  1,
  209,
  1239,
  2696,
  247,
  1886,
  2,
  1658,
  306,
  2332,
  786,
  81,
  28,
  16,
  38,
  2,
  611,
  122,
  1,
  105,
  2960,
  645,
  25,
  2172,
  740,
  7,
  2527,
  2972,
  1207,
  66,
  87,
  1518,
  1207,
  303,
  289,
  73,
  85,
  488,
  1200,
  10,
  2510,
  66,
  1,
  10,
  37,
  13,
  205,
  260,
  2997,
  169,
  469,
  619,
  76,
  855,
  231,
  1511,
  408,
  331,
  934,
  430,
  130,
  4867,
  271,
  25,
  172,
  71,
  1511,
  2317,
  866,
  1142,
  7,
  2527,
  3682,
  263,
  77,
  943,
  3097,
  231,
  1305,
  70,
  249,
  1368,
  1187,
  1337,
  722,
  415,
  45,
  44,
  4,
  1,
  82,
  15,
  3697,
  172,
  1184,
  1916,
  68,
  120,
  2263,
  1050,
  66,
  210,
  1566,
  2327,
  4199,
  196,
  4,
  11,
  100,
  66,
  7,
  2527,
  397,
  288,
  13,
  1338,
  615,
  382,
  102,
  20,
  4,
  198,
  4,
  25,
  1,
  1538,
  77,
  1427,
  110,
  288,
  238,
  93,
  104,
  44,
  1752,
  2,
  368,
  1124,
  535,
  182,
  2138,
  1864,
  1995,
  855,
  1050,
  66,
  2675,
  175,
  1641,
  238,
  4814,
  674,
  2,
  465,
  253,
  3466,
  547,
  40,
  1293,
  40,
  73,
  4,
  128,
  17,
  2194,
  40,
  345,
  2696,
  1752,
  146,
  4994,
  1739,
  125,
  70,
  239,
  52,
  91,
  4815,
  99,
  712,
  96,
  7,
  2527,
  451,
  1112,
  1,
  763,
  231,
  521,
  3495,
  670,
  4484,
  5,
  8,
  382,
  2,
  42,
  15,
  20,
  401,
  850,
  861,
  15,
  1518,
  304,
  231,
  107,
  1121,
  685,
  469,
  3,
  216,
  1591,
  52,
  2550,
  22,
  1,
  152,
  78,
  5,
  1406,
  177,
  85,
  3106,
  159,
  365],
 [2,
  677,
  32,
  83,
  1197,
  907,
  2003,
  277,
  2627,
  4427,
  659,
  106,
  141,
  1119,
  931,
  178,
  162,
  1142,
  3277,
  161,
  99,
  531,
  301,
  1541,
  48,
  168,
  1036,
  1098,
  425,
  204,
  13,
  4010,
  692,
  167,
  521,
  4358,
  490,
  2023,
  515,
  153,
  238,
  245,
  401,
  374,
  261,
  781,
  2,
  166,
  22,
  204,
  150,
  24,
  198,
  1400,
  1693,
  130,
  188,
  3974,
  1891,
  1072,
  4836],
 [1,
  4485,
  176,
  376,
  371,
  2500,
  5,
  8,
  128,
  96,
  390,
  698,
  6,
  149,
  262,
  21,
  850,
  4,
  59,
  4705,
  1467,
  253,
  3063,
  1547,
  728,
  1728,
  15,
  705,
  141,
  269,
  1006,
  312,
  1783,
  46,
  269,
  619,
  42,
  155,
  115,
  2440,
  205,
  1728,
  664,
  6,
  313,
  383,
  50,
  110,
  52,
  16,
  271,
  1,
  1314,
  1878,
  1024,
  402,
  220,
  1197],
 [277,
  430,
  124,
  32,
  114,
  2460,
  321,
  36,
  403,
  7,
  250,
  108,
  767,
  218,
  1804,
  1869,
  955,
  2229,
  3713,
  948,
  94,
  204,
  1,
  179,
  248,
  178,
  899,
  278,
  116,
  1412,
  12,
  39,
  3133,
  165,
  2662,
  204,
  924,
  993,
  2388,
  1143,
  1059,
  4102,
  2,
  471,
  206,
  2376,
  993,
  2388,
  204,
  1,
  1020,
  1682,
  198,
  99,
  2,
  2033,
  84,
  1134,
  1478,
  54,
  1558,
  864,
  622,
  1331,
  3221,
  73,
  2389,
  789,
  94,
  993,
  2388,
  15,
  2662,
  204,
  746,
  20,
  114,
  12,
  4816,
  89,
  1530,
  157,
  1059,
  389,
  2769,
  204,
  220,
  3742,
  993,
  2388,
  2118,
  1326,
  220,
  2590,
  221,
  425,
  157,
  4102,
  21,
  648,
  4453,
  659,
  531,
  57,
  253,
  319,
  216,
  99,
  2337,
  3723,
  782,
  869,
  3611,
  2,
  2343,
  9,
  588,
  2073,
  993,
  2388,
  439,
  214,
  386,
  63,
  533,
  422,
  1874,
  216,
  4303,
  1393,
  2682,
  1618,
  3723,
  752,
  100,
  1932,
  57,
  3054,
  682,
  1865,
  42,
  265,
  4143,
  439,
  55,
  475,
  2112,
  173,
  1151,
  297,
  157,
  1454,
  181,
  3054,
  57,
  203,
  54,
  298,
  3272,
  4753,
  204,
  90,
  743,
  597,
  668,
  31,
  2921,
  4284,
  1412,
  54,
  114,
  1137,
  3271,
  204,
  3024,
  1152,
  4103,
  28,
  1178,
  1229,
  302,
  276,
  268,
  1306,
  2590,
  4995,
  1688,
  3143,
  3834,
  92,
  323,
  2951,
  3766,
  1115,
  7,
  204,
  579,
  341,
  368,
  1023,
  204,
  665,
  1092,
  2353,
  484,
  220,
  559,
  4601,
  2118,
  216,
  15,
  2769,
  864,
  53,
  1307,
  20,
  204,
  4428,
  63,
  2551,
  204,
  1115,
  15,
  420,
  986,
  841,
  1307,
  3357,
  73,
  1996,
  932,
  4219,
  1169,
  2,
  765,
  391,
  153,
  1319,
  42,
  1369,
  1678,
  28,
  37,
  12,
  1538,
  362,
  48,
  2,
  63,
  3452,
  9,
  1829,
  840,
  555,
  24,
  2318,
  840,
  279,
  36,
  23,
  1343,
  993,
  2388,
  1025,
  135,
  5,
  802,
  3370,
  204,
  360,
  874,
  1732,
  924,
  152,
  2746,
  19,
  278,
  216,
  381,
  20,
  3024,
  910,
  204,
  1020,
  1770,
  3453,
  291,
  3454],
 [2933,
  2389,
  675,
  618,
  2484,
  665,
  1,
  703,
  72,
  1426,
  2426,
  1015,
  1163,
  2440,
  188,
  48,
  1610,
  525,
  1669,
  1880,
  3663,
  2755,
  1230,
  234,
  468,
  2338,
  489,
  1299,
  525,
  92,
  251,
  525,
  793,
  4602,
  669,
  244,
  188,
  660,
  3019,
  1669,
  790,
  1798,
  1263,
  3064,
  92,
  104,
  1679,
  133,
  223,
  3813,
  276,
  188,
  1143,
  1669,
  1839,
  1555,
  363,
  828,
  54,
  4687,
  1594,
  117,
  94,
  1334,
  92,
  105,
  35,
  47,
  319,
  21,
  1329,
  3921,
  1223,
  4603,
  54,
  543,
  793,
  39,
  754,
  1638,
  82,
  307,
  117,
  71,
  819,
  7,
  3754,
  3496,
  298,
  86,
  15,
  2394,
  3545,
  1003,
  834,
  986,
  869,
  1304,
  128,
  125,
  518,
  1719,
  94,
  1669,
  4200,
  4429,
  54,
  54,
  9,
  578,
  580,
  597,
  594,
  350,
  730,
  3263,
  806,
  511,
  51,
  584,
  1401,
  4817,
  2164,
  94,
  2142,
  277,
  347,
  1023,
  7,
  2485,
  115,
  969,
  3823,
  149,
  580,
  1023,
  409,
  736,
  1044,
  1880,
  92,
  1530,
  57,
  253,
  196,
  954,
  9,
  63,
  417,
  167,
  139,
  125,
  893,
  4966,
  822,
  640,
  2682,
  221,
  329,
  116,
  3975,
  3976],
 [3,
  1875,
  2,
  45,
  22,
  1264,
  352,
  433,
  18,
  73,
  3,
  1063,
  154,
  3287,
  4144,
  352,
  19,
  577,
  2042,
  928,
  9,
  538,
  2770,
  909,
  887,
  2628,
  7,
  2,
  629,
  58,
  39,
  2682,
  489,
  2179,
  945,
  489,
  2628,
  489,
  189,
  1494,
  3454,
  2104,
  58,
  39,
  1455,
  489,
  2639,
  2825,
  897,
  489,
  3864,
  2,
  4115,
  12,
  92,
  796,
  873,
  475,
  245,
  141,
  268,
  2422,
  489,
  2423,
  2869,
  2869,
  323,
  1455,
  860,
  108,
  732,
  202,
  2,
  36,
  1809,
  1858,
  732,
  46,
  757,
  491,
  2810,
  4507,
  202,
  4754,
  2686,
  4868,
  4837,
  486,
  4175,
  19,
  1541,
  4838,
  7,
  1098,
  668,
  51,
  1049,
  1257,
  1789,

In [ ]:
# 3. Padding
X_pad = pad_sequences(sequences, maxlen=100)

# 4. Model
model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=64))
model.add(SimpleRNN(64))
model.add(Dense(1, activation='sigmoid'))

# 5. Compile
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# 6. Train (CORRECT)
h1 = model.fit(X_pad, y, epochs=10)

Epoch 1/10
 195/1550 ━━━━━━━━━━━━━━━━━━━━ 44s 33ms/step - accuracy: 0.5452 - loss: 0.6804