<a href="https://colab.research.google.com/github/princeiiitk/Sentiment-Analysis/blob/main/Sentimat_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/princeiiitk/Sentiment-Analysis

Cloning into 'Sentiment-Analysis'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 5), reused 5 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (15/15), 25.57 MiB | 30.31 MiB/s, done.
Resolving deltas: 100% (5/5), done.

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/content/Sentiment-Analysis/IMDB Dataset.csv')

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [6]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(418)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:

df.duplicated().sum()

np.int64(0)

# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [11]:
import re
def remove_tags(raw_text):
  cleaned_text=re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [12]:
df['review']=df['review'].apply(remove_tags)

In [13]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [14]:
df['review']=df['review'].apply(lambda x:x.lower())

In [15]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

sw_list = stopwords.words('english')

df['review']=df['review'].apply(lambda x:[wordlist for wordlist in x.split() if wordlist not in sw_list]).apply(lambda x:' '.join(x))

In [ ]:
df['review']

In [ ]:
X=df['review']
y=df['sentiment']

In [ ]:
X

In [ ]:
y

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
y_test

In [ ]:
X_train.shape

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
X_train_transformed=cv.fit_transform(X_train).toarray()
X_test_transformed=cv.transform(X_test).toarray()

In [ ]:
X_train_transformed.shape

# Naive Bayes (GaussianNB) Model Training for Classification

In [ ]:
from sklearn.naive_bayes import GaussianNB


model=GaussianNB()
model.fit(X_train_transformed,y_train)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred=model.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

In [ ]:
confusion_matrix(y_test,y_pred)

# Naive Bayes (MultinomialNB) Model Training for Text Classification

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model2=MultinomialNB()
model2.fit(X_train_transformed,y_train)

In [ ]:
y_pred=model.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

# Random Forest Classifier Model Training for Machine Learning Classification

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model3=RandomForestClassifier()
model3.fit(X_train_transformed,y_train)

In [ ]:
y_pred=model.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

In [ ]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

In [ ]:
cv=CountVectorizer(ngram_range=(1,2),max_features=5000)
X_train_bow=cv.fit_transform(X_train).toarray()
X_test_bow=cv.transform(X_test).toarray()
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

# Using RNN

In [ ]:
!pip install tensorflow

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

# 1. Tokenize
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(X)

# 2. Convert to sequences
sequences = tokenizer.texts_to_sequences(X)
# sequences

In [ ]:
# 3. Padding
X_pad = pad_sequences(sequences, maxlen=100)

# 4. Model
model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=64))
model.add(SimpleRNN(64))
model.add(Dense(1, activation='sigmoid'))

# 5. Compile
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# 6. Train (CORRECT)
h1 = model.fit(X_pad, y, epochs=10)

In [ ]:
# using LSTM